version: "3.4"
services:
  ldap:
    restart: always
    hostname: dev.sttx.local
    build:
      context: .
      dockerfile: Dockerfile  
    privileged: true
    expose:
      - "389"
    ports:
      - "389:389"
    environment:
      SMB_ADMIN_PASSWORD: admin123!
      AD_DOMAIN: STTX-LOCAL